apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/luckyPrice/k8s-deployments'
    targetRevision: HEAD
    path: apps/my-web-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RollbackOnFailure=true  # 배포 실패 시 자동 롤백